[global]
type=global
user_agent=SupportHubPBX

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[1001]
type=endpoint
context=supporthub-agents
disallow=all
allow=ulaw
auth=1001-auth
aors=1001-aor

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=ChangeMe1001

[1001-aor]
type=aor
max_contacts=1

[1002]
type=endpoint
context=supporthub-agents
disallow=all
allow=ulaw
auth=1002-auth
aors=1002-aor

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=ChangeMe1002

[1002-aor]
type=aor
max_contacts=1

[1003]
type=endpoint
context=supporthub-agents
disallow=all
allow=ulaw
auth=1003-auth
aors=1003-aor

[1003-auth]
type=auth
auth_type=userpass
username=1003
password=ChangeMe1003

[1003-aor]
type=aor
max_contacts=1
